### ISSUE TITLE
User Story 6 - Music News App contains an Event Page

### ISSUE THREAD

**Issue by IC-Socaciu** [IC-Socaciu/all-access-pass-1#11]
## Value proposition

As a musician I want to have the possibility to add my gig to the event list so that I can inform the fans, regular concert goers and promote my music .

## Description

![US 6 AAP](https://github.com/IC-Socaciu/all-access-pass-1/assets/125737167/6712d0fb-0a0c-464e-8a85-420232a72cc1)
## Acceptance criteria

- [ ] Add option to add an event 
- [ ] An Add Events form with required info must be available to fill out or select options from

## Tasks

- [ ] Create feature branch feature/add-event
- [ ] Create an Add Event form

Size: M

**Comment by Roland-Hufnagel** [comment]
This is a useful feature and a good structured userstory. Only it it a bit short. Since it is a 'size: M'  you should define some more acceptance-criterias and tasks. Saying: 'Do the job' is not enough. Please specify some more tasks and criterias, e.g. ``Navigation-Bar contains a link to the 'add form'-page``,``Clicking Save will lead to the homepage``(both are criterias). By the way: I miss a save-button in your wireframe. Tasks could be: ``Create a addForm-page``,``Create a form-component``,`Àdd the link to the nav-bar``, ...

**Comment by IC-Socaciu** [comment]
Thank you for the feedback! Rewriting now.
