### ISSUE TITLE
User story 7 - Music News App Add Event to page functionality

### ISSUE THREAD

**Issue by IC-Socaciu** [IC-Socaciu/all-access-pass-1#12]
## Value proposition

As a musician I want to be able to add my gig to the event list so that I can inform the fans, regular concert goers and promote my music

## Description

![US7 AAP](https://github.com/IC-Socaciu/all-access-pass-1/assets/125737167/80c48631-3100-424f-a601-198c73754cf0)

## Acceptance criteria

- [ ] A button that allows users to submit their event should be available
- [ ] With a single click the event is added to the page containing upcoming events
- [ ] Once form is submitted the user is taken back the the Events page where the new entry is displayed

## Tasks

- [ ] Create feature branch feature/submit-event
- [ ] Create an Add Event / Submit button  
- [ ] Add functionality to button so that onClick the newly added info is listed on the events page

Size: M

**Comment by Roland-Hufnagel** [comment]
Okay, now I see you want to implement the submit functionality in this US. This US itself is okay, but what is the value from your last US? To have a form that cannot be submitted is not very useful, right? So I recommend to put both together.

**Comment by IC-Socaciu** [comment]
Thank you for the feedback. I knew what you meant when you added the suggestions on US6 and I knew that it is split in half more or less correctly. I just felt it would be a too hefty story to keep it all in one so decided to have two somewhat equal M stories instead.
