### ISSUE TITLE
User Story 8 - Music News App User Interaction

### ISSUE THREAD

**Issue by IC-Socaciu** [IC-Socaciu/all-access-pass-1#15]
## Value proposition

As a music fan I want to be able to share feedback and interact with fellow minded readers after reading the articles and navigate back to the preview page.

## Description

![US 8 AAP](https://github.com/IC-Socaciu/all-access-pass-1/assets/125737167/caea2e41-5252-4eba-a9cf-caab6e30f8d6)

## Acceptance criteria

- [ ] A button that allows to like the article should be present
- [ ] A counter should display the current likes +1
- [ ] A comment area should be available to write comments 
- [ ] A possibility to submit these comments and share them publicly should be available

## Tasks

- [ ] Create feature branch feature/interaction
- [ ] Create comment section and input for readers
- [ ] Add functionality and allow comments to be written and displayed
- [ ] Create a like button component to interact with article 
- [ ] Add functionality to like and count likes

Size: M

**Comment by JudithRe** [comment]
I think maybe the favourite button and the comment section are two separate user stories. 

- The comment section would be a form + the display? (Maybe you could make that a little clearer in the tasks.
- I don't think you need to put "to interact with the article" - a button component

**Comment by CJAkkuec** [comment]
I don't want to annoy you with one more thing to consider, but ...

>  Interaction with this button allows users to like the article

How does the user know they liked the article? It may be apparent to you that the total likes present on the article will increase, but that should be described as "acceptable/desired behavior", such as

>  Interaction with this button allows users to like/unlike the article, which will increase/decrease the total amount of likes

and: if the user gets to like something, they should probably also get to unlike it.

Additionally, what happens if there are no likes? Does it render as **"👍 0"** or **"👍 Be the first to like this article!"**?

---

Some advanced notes to consider (beyond MPV status, perhaps):

- if someone is click-botting their own articles, is there any measure to prevent that?
- if an article reaches a huge amount of likes, is there some sort of obfuscation going to happen, such as moving from **"👍 1 000 000"** to **"👍 1m"**?

**Comment by IC-Socaciu** [comment]
This makes TOTAL sense. Hope the rewritten US is a bit better.

**Comment by CJAkkuec** [comment]
It is! I didn't necessarily imply that the 👎 is required, because you may as well just have the 👍 be dual purpose in how clicking it will add a like, and clicking it again will take the like away again. This is mostly a decision about how you want the user to express themselves and to what end.

Maybe amend the value proposition that it mentions this US is about a like/unlike button specifically.

Also,
and sorry for being such a stickler about details, but depending on which route you go for 👍 / 👎 ...
> Add functionality to the like/dislike button that increments and decrements the state of likes/dislikes via a click handler.

**Comment by NicoleHoerner** [comment]
Thumbs up 👍. I think US8 is good to go.
