### ISSUE TITLE
User Story 9 - Music News App Comment Card Section on each article 

### ISSUE THREAD

**Issue by dramaticgarlic** [IC-Socaciu/all-access-pass-1#17]
## Value proposition

As a music fan I want to be able to share feedback in order to interact with fellow minded readers after reading the articles.

## Description

![US 9 AAP](https://github.com/IC-Socaciu/all-access-pass-1/assets/125737167/06662eb1-b929-4ac2-a73e-53d849b7077c)

## Acceptance criteria

- [ ] A comment text area should be available to write comments 
- [ ] A name text box should be available so that users can sign and stand by their opinion
- [ ] A submit button to share comments publicly should be available

## Tasks

- [ ] Create feature branch feature/comments
- [ ] Create comment text area with a username input for readers to write a message  and their name
- [ ] Add functionality and allow comments to be and displayed as a message card once Submit button is clicked and the associated name

Size: M

**Comment by NicoleHoerner** [comment]
Maybe it is too "petty"/detailed: but can I remain anonymous? 
I am also thinking for the quality acceptance. Do I have to put a name? Maybe I want to leave a comment but without stating my name.
