### ISSUE TITLE
User Story 1 - News App on main page a list of articles and overview is displayed

### ISSUE THREAD

**Issue by dramaticgarlic** [IC-Socaciu/all-access-pass-1#2]
## Value proposition

As a music fan I want to look at the article overview in order to get a glance over the news in music

## Description

![Image](https://github.com/IC-Socaciu/all-access-pass-1/assets/125737167/d091d78f-6989-4459-94b1-27717b239ec9)

## Acceptance criteria

- [ ] The article heading of each article is shown
- [ ] The article image of each article is shown
- [ ] The article short description of each article is shown
- [ ] The displayed content is readable

## Tasks

- [ ] Create feature branch feature/article-page
- [ ] Shape dummy data
- [ ] Display articles on page

Size: M
