### ISSUE TITLE
User Story 10 - Music News App Add Pagination

### ISSUE THREAD

**Issue by IC-Socaciu** [IC-Socaciu/all-access-pass-1#20]
## Value proposition

As a user of this news app I want to be able to navigate through the content pages so that I can have an overview of the overall content.

## Description

![Image](https://github.com/IC-Socaciu/all-access-pass-1/assets/125737167/1a00cba1-95a9-4de4-86b8-adf034fb6502)

## Acceptance criteria

- [ ]  A link must be present on the preview page showing current page and total  pages (eg: < 1 / 5 >)
- [ ] With a single click the reader can navigate between pages go forward and backward

## Tasks

- [ ] Create feature branch feature/pagination 
- [ ] Create a link to navigate between pages 
- [ ] Update ArticlePreview component to display only the articles for the current page
- [ ] Add functionality and allow a smooth navigation between pages

Size: M
