### ISSUE TITLE
User Story 11 - Music News App Music Style Generator Suggestion

### ISSUE THREAD

**Issue by IC-Socaciu** [IC-Socaciu/all-access-pass-1#22]
## Value proposition

As a music fan I want to have some recommendations in order to find something new to listen to and expand my music knowledge 

## Description

![Image](https://github.com/IC-Socaciu/all-access-pass-1/assets/125737167/374acae5-8d77-4487-a2b2-ad030b6318fd)

## Acceptance criteria

- [ ] A new page dedicated to the random music style generator must be present (actual name TBD)
- [ ] The music style API must be linked to the 'Discover` page
- [ ] With a single click the reader discovers a new music genre as a suggestion for something new that they can individually research for
- [ ] The style must be generated and displayed

## Tasks

- [ ] Create feature branch feature/genre-api
- [ ] Create a new page 'Discover' (actual name TBD)
- [ ] Fetch information from API and display the music genre on the page
- [ ] Add a generate Button and add functionality to allow users to access a new random style with each click 

Size: M

**Comment by JudithRe** [comment]
lgtm
