### ISSUE TITLE
US 12 General Styling

### ISSUE THREAD

**Issue by IC-Socaciu** [IC-Socaciu/all-access-pass-1#26]
## Value proposition

As a reader of this music news app I want to be able to easily access the app in order to have a good experience while using it

## Acceptance criteria

- [ ] The articles must be legible
- [ ] The style must be consistent and responsive
- [ ] All articles, pages and elements must be accessible and visible

## Tasks

- [ ] Implement techniques to improve legibility
- [ ] Create a responsive design
- [ ] Add simple design elements that match and are consistent

Size: M
