### ISSUE TITLE
User Story 13 - Delete Comment button available on full article comment section 

### ISSUE THREAD

**Issue by IC-Socaciu** [IC-Socaciu/all-access-pass-1#28]
## Value proposition

As a music fan I want to be able to delete the comment that I posted in case I change my mind about submitting a comment.

## Description

![US 13 AAP](https://github.com/IC-Socaciu/all-access-pass-1/assets/125737167/226a394c-0fa5-4a33-a09f-003b57508582)

## Acceptance criteria

- [ ] A delete comment button must be preset in the comment section
- [ ] The style must be consistent and responsive

## Tasks

- [ ] Create delete comment button
- [ ] Add functionality so that the moment the comment is added the user an delete their own comment
- [ ] Add consistent design to button 

Size: M
