### ISSUE TITLE
User Story 14 - Add edit button to comment

### ISSUE THREAD

**Issue by IC-Socaciu** [IC-Socaciu/all-access-pass-1#34]
## Value proposition

As a music fan I want to be able to edit the comment that I posted in case I change my mind about what was written.

## Description

![Image](https://github.com/IC-Socaciu/all-access-pass-1/assets/125737167/7be2fd6f-3eb2-4fbd-93f9-0e5932b4aaa1)

## Acceptance criteria

- [] An edit comment button must be present in the comment once the user submits it
- []  The style must be consistent and responsive
- [] The message should respond and permit changes to be made

## Tasks

- [ ] Create an Edit comment button
- [ ]  Add functionality so that the moment the comment is added the user can edit their own comment
- [ ] Add simple design elements that match and are consistent

Size: M
