### ISSUE TITLE
User Story 2

### ISSUE THREAD

**Issue by IC-Socaciu** [IC-Socaciu/all-access-pass-1#4]
## Value proposition

As a music fan I want to be able to read the articles in their entirety.

## Description

![US 2 a AAP](https://github.com/IC-Socaciu/all-access-pass-1/assets/125737167/1f2bfb26-1ca2-4104-90a7-f264198701d0)

![US 2 b AAP](https://github.com/IC-Socaciu/all-access-pass-1/assets/125737167/520e8bcf-083b-4ffc-89a0-8701a1abef1b)

## Acceptance criteria

- [ ] A button that allows to fully read article should be available on all previews
- [ ] With a simple click the full article is accessible 

## Tasks

- [ ] Create feature branch feature/readfull-btn
- [ ] Create a button component
- [ ] Add functionality
- [ ] Create full article component with title, image, text body
- [ ] Shape dummy data
- [ ] Display articles on page

Size: M
