### ISSUE TITLE
User Story 3

### ISSUE THREAD

**Issue by IC-Socaciu** [IC-Socaciu/all-access-pass-1#5]
## Value proposition

As a reader of this news app I want to be able to access the main page that contains the article summary as well and move between pages that contain the full article and back. 

## Description

[image of wireframe]

## Acceptance criteria

- [ ] A home button must be available on all pages including the full article page
- [ ] Buttons should have a consistent look and be easily spotted by readers 

## Tasks

- [ ] Create button elements to connect pages for a smooth navigation
- [ ] Add functionality to all buttons

Size: S

**Comment by CJAkkuec** [comment]
> [image of wireframe]
👀  Where is it?

> As a reader of this news app I want to be able to access the main page that contains the article summary as well and move between pages that contain the full article and back.

I think it'd be just fine to keep the value proposition focused on the single benefit of routing, such as

> As a reader of this news app I want to have access to a navigation and other navigational elements such as a "back" button so that I can go back and forth between the article overview and the article pages.

Essentially, this US could include building a navbar (navigation) that includes a home button. This navigation can be scaled as soon as there are more pages that you can route to and from.

**Comment by donacrisante** [comment]
"A navbar should be available on top of the page at all times"

Do you mean "at the bottom of the page" maybe? If yes, I would just change this detail.

**Comment by IC-Socaciu** [comment]
Great catch! Thank you!  It was a last minute decision to switch position so yes, it is meant to be at the bottom.  :)

**Comment by donacrisante** [comment]
Perfect! I put a green tick ;)
