### ISSUE TITLE
User Story 4 - News App search function

### ISSUE THREAD

**Issue by IC-Socaciu** [IC-Socaciu/all-access-pass-1#6]
## Value proposition

As a news reader I want to be able to search by different keywords in order to find the matching articles that interest me.

## Description

![US 4 AAP](https://github.com/IC-Socaciu/all-access-pass-1/assets/125737167/a39060d7-c7d8-4e1c-8f14-353c3bbf4b94)

## Acceptance criteria

- [ ] A search bar should be available on the top part of the screen
- [ ] A search button should be placed next to the search bar
- [ ] The possibility to search and filter for the desired content should be available

## Tasks

- [ ] Create feature branch feature/search
- [ ] Create a search component 
- [ ] Add functionality to the search bar
- [ ] Create search button next to the search bar
- [ ] Add functionality and allow reader to search for typed in terms

Size: M
