### ISSUE TITLE
User Story 5 - News App Event Page Addition

### ISSUE THREAD

**Issue by IC-Socaciu** [IC-Socaciu/all-access-pass-1#8]
## Value proposition

As a concert goer I want to be able to see what concerts are available in my area so that I can be informed of upcoming events and consider my options.

## Description

![US 5 AAP](https://github.com/IC-Socaciu/all-access-pass-1/assets/125737167/927d4c68-111e-4fb7-a45c-e16e98e3118f)

## Acceptance criteria

- [ ] An Events page must be available for the readers
- [ ] An overview of upcoming concerts, venues, dates from local live clubs should be displayed

## Tasks

- [ ] Create feature branch feature/event
- [ ] Create an Event page  
- [ ] Add Event lists with date, location, band etc

Size: M
